version: "3"
services:
  node:
    image: "node"
    container_name: "nodejs"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3030:3030"
    tty: true
    command: "npm run start"